{{- if .Values.tools.enabled -}}
{{- $environment := include "app.environment" . -}}
{{- $cloudProviderFlavor := include "app.cloudProviderFlavor" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    component: tools-service
    environment: {{ $environment }}
    release: {{ .Release.Name }}
spec:
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.tools.servicePort }}
      targetPort: 8080 # DO NOT CHANGE, AS IT'S HARDCODED IN APPLICATION.
      protocol: TCP
      name: http
      {{- if eq $cloudProviderFlavor "minikube" }}
      nodePort: {{ .Values.tools.nodePort }}
      {{- end }}
  selector:
    app: {{ template "app.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-tools
{{- end }}
