apiVersion: v2
description: Helm chart to deploy Catalog App
name: mc-web-tools
version: 1.11.2
appVersion: 1.11.2
dependencies:
  - name: helm-common
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm
